Render names in authorization list
subconsciousnetwork/subconscious pull request #1066
Opened 2024-01-09 23:32 UTC by bfollington

2024-01-13 01:06 UTC, gordonbrander requested changes
Looks good, just recommend adding one test

2024-01-13 01:06 UTC, gordonbrander commented on xcode/Subconscious/Shared/Services/Noosphere/Sphere.swift
> +    public func authorizationName(authorization: Authorization) async throws -> String {
Let's add a test for this method

2024-01-15 06:16 UTC, bfollington commented on xcode/Subconscious/Shared/Services/Noosphere/Sphere.swift
> +    public func authorizationName(authorization: Authorization) async throws -> String {
Good call, done!

2024-01-16 21:58 UTC, gordonbrander approved these changes
LGTM

2024-01-16 22:01 UTC, merged