Implement peer discovery
subconsciousnetwork/subconscious pull request #1117
Opened 2024-02-16 08:13 UTC by bfollington

2024-02-20 05:13 UTC, bfollington commented on xcode/Subconscious/Shared/Components/Common/Profile/Sheets/FollowNewUserFormSheet.swift
> +        }
Pre-populate the form with the best name + DID

2024-02-20 05:16 UTC, bfollington commented on xcode/Subconscious/Shared/Components/Notebook/NotebookNavigationView.swift
> +                .ignoresSafeArea(.keyboard, edges: .bottom)
An attempt to fix the strange cutoff BG issue we've seen.

2024-02-20 05:16 UTC, bfollington commented on xcode/Subconscious/Shared/Services/DataService.swift
> +//                    ))
TODO: implement

2024-02-20 15:03 UTC, gordonbrander requested changes
A few comments and questions. Otherwise LGTM.

2024-02-21 00:50 UTC, bfollington commented on xcode/Subconscious/Shared/Components/AppTabView.swift
Sounds good to me, I think there's room for visual improvement on the `DiscoverUserView` component in general but I didn't want to overcook the first pass.

2024-02-22 16:32 UTC, gordonbrander approved these changes
LGTM

2024-02-22 23:06 UTC, merged