Fix tap targets for Story Views
subconsciousnetwork/subconscious pull request #556
Opened 2023-04-26 06:47 UTC by bfollington

Background needs to be inside the button for it to count as tappable.

2023-04-26 13:44 UTC, gordonbrander requested changes

2023-04-26 23:59 UTC, bfollington commented on xcode/Subconscious/Shared/Components/Common/Story/StoryEntryView.swift
> -        .background(Color.background)
Nice, added. The background call is still better inside the button imo.

2023-04-26 23:59 UTC, bfollington commented on xcode/Subconscious/Shared/Components/Common/Story/StoryUserView.swift
> -        .background(Color.background)
Nice, added. The background call is still better inside the button imo.

2023-04-27 12:34 UTC, gordonbrander approved these changes

2023-04-27 12:46 UTC, merged