Re-arrange onboarding steps
subconsciousnetwork/subconscious pull request #918
Opened 2023-10-02 05:47 UTC by bfollington

Re-arrange order of steps, still roughing out the details

2023-10-03 23:56 UTC, bfollington commented on xcode/Subconscious/Shared/Components/AppUpgradeView.swift
> +            Spacer()
Matching the layout of the FirstRun view

2023-10-03 23:56 UTC, bfollington commented on xcode/Subconscious/Shared/Components/AppUpgradeView.swift
> +        ))
Matching the layout of the FirstRun view

2023-10-03 23:58 UTC, bfollington commented on xcode/Subconscious/Shared/Components/FirstRun/FirstRunOrbitEffectView.swift
> +        }
I wanted to do:

```swift
[GenerativeProfilePic](
    repeating: GenerativeProfilePic(did: Did.dummyData(), size: 20),
    count: 15
)
```

But I need the `repeating:` parameter to be a new instance each time.

2023-10-06 18:40 UTC, gordonbrander requested changes
Playtested on-device. Looks and feels great.

I would like to make the following adjustments to the copy... other than that, LGTM!

### Welcome to Subconscious

Subconscious is a place to garden thoughts and share them with others.

It’s powered by Noosphere, a decentralized protocol, so your data belongs to you.

### Create Sphere

Subconscious stores your notes in your personal sphere.

Your sphere is stored on your device, and connects to other spheres over a decentralized network.

### Recovery Phrase

This is your sphere's secret recovery phrase. You can use it to recover your data if you lose access.

It's for your eyes only. We don't store it. Write it down or add it to your password manager.

### Your Profile

Give your sphere a nickname:

### Invite Code

Get connected to Noosphere.

Enter your invite code to create your gateway.

### Done

Creating your gateway...

You can start exploring offline.

_or_

Connected!

Welcome to Subconscious.

2023-10-09 00:50 UTC, bfollington commented
@gordonbrander nice, I like it. Updated & re-requested review.

2023-10-09 01:44 UTC, gordonbrander approved these changes
LGTM

2023-10-09 05:44 UTC, merged